Lesson 15: Background jobs (ActiveJob and Sidekiq)
georgiybykov/qna pull request #17
Opened 2021-08-09 00:44 UTC by georgiybykov

**Реализовать следующие истории, используя фоновые задачи:**

- Отправка ежедневного письма-дайджеста всем пользователям. Дайджест содержит список всех вопросов, созданных за последние сутки.
- Автор вопроса получает уведомление на `email` при появлении нового ответа на свой вопрос.
- Любой залогиненный пользователь может подписаться на обновления вопроса. При этом он будет получать уведомления по `email` при появлении новых ответов на этот вопрос. Кол-во вопросов, на которые может быть подписан пользователь не ограничено.
- Пользователь может отписаться от получения уведомлений об обновлении вопроса, если он на них подписан. Отписаться можно только от вопроса, на обновления которого пользователь подписан.
- Автор вопроса также может отписаться от получения уведомлений о новых ответах на его вопрос.

**Примечание:**

Отправка писем помещается автоматический в отдельную очередь (`mailers`), поэтому, чтобы `sidekiq` отправлял письма из этой очереди, при запуске нужно явно это указать через параметр `-q`:

```
sidekiq -q default -q mailers
```

2021-08-15 13:15 UTC, vkurennov requested changes

2021-08-15 13:15 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  def send_notification
это надо делать в коллбеках моделей, а не в контроллере, потому что логика должна быть всегда одна, вне зависимости от того, как объект создается.

2021-08-15 13:15 UTC, vkurennov commented on app/controllers/api/v1/answers_controller.rb
> +      def send_notification
вот видишь - тебе пришлось дублировать код, а если сделать это в моделях, то этого можно избежать. если логика отправки нтификаций изменится, тебе надо будет в двух местах ее править, а не в одном, вот чем плохо дублирование

2021-08-15 13:15 UTC, vkurennov commented on app/controllers/api/v1/questions_controller.rb
> +      def create_subscription
опять же это делается в моделях, а не в контроллерах

2021-08-15 13:15 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +  def create_subscription
вынеси в модель и избавься от дублирования

2021-08-15 13:15 UTC, vkurennov commented on app/models/subscription.rb
> +  validates :user, :question, presence: true
ассоциации belongs_to не надо валидировать на presence, они по-умолчанию обязательные и валидируются автоматоически

2021-08-16 00:20 UTC, georgiybykov commented on app/controllers/api/v1/answers_controller.rb
> +      def send_notification
Полностью согласен. В конце задания понял, что изначально ошибся, но переписать забыл :(
Спасибо, что заметили, исправил!

2021-08-16 00:25 UTC, georgiybykov commented on app/models/subscription.rb
> +  validates :user, :question, presence: true
Точно, это с версии Rails 5.0, вроде бы, добавлено. Спасибо, исправил.

2021-08-16 08:28 UTC, vkurennov approved these changes

2021-08-18 22:55 UTC, merged