Lesson 6: Integration (acceptance) testing
georgiybykov/qna pull request #4
Opened 2021-02-28 22:29 UTC by georgiybykov

**1. Реализовать следующие истории, начиная с `acceptance-тестов` (если они уже реализованы, покрыть `acceptance-тестами`):**
  - Пользователь может создавать вопрос.
  - Пользователь может просматривать список вопросов.
  - Пользователь, находясь на странице вопроса, может написать ответ на вопрос (т.е. форма нового ответа должна быть прямо на странице вопроса, без перехода на другую страницу).
  - Пользователь может просматривать вопрос и ответы к нему.

 **2. Добавить аутентификацию к проекту, покрыть `acceptance-тестами` следующие сценарии:**
  - Пользователь может войти в систему.
  - Пользователь может выйти из системы.
  - Пользователь может зарегистрироваться в системе.

 **3. Реализовать следующие истоиии:**
  - Только аутентифицированный пользователь может создавать вопросы и ответы.
  - Автор может удалить свой вопрос или ответ, но не может удалить чужой вопрос/ответ.

______________________________________________________________________________________________________

**_Примечание:_** 
- Во всех формах ставьте опцию `local: true`, чтобы избежать возможных проблем с отображением ошибок при реальной работе в браузере.

**_Рекомендации:_**
 - Можно записать основные сценарии, без реализации, а затем писать их один за другим. Для этого просто напишите  
`scenario 'some description'`. Такие сценарии будут отображаться как `pending`, то есть ждущие реализации. Это для того, чтобы вы не забыли их реализовать.
 - Написали сценарий, перешли на уровень `unit-тестов`. Здесь двигаемся мелкими шагами `'тест-код-рефакторинг, тест-код-рефакторинг'`. Некоторые вещи можно будет описать сразу, например, валидации и ассоциации, а какие-то будут сложнее, здесь лучше двигаться постепенно.
 - Далее описываем следующий сценарий и опять на уровень `unit-тестов` и так далее, пока не реализуем все сценарии.
 - После того, как все сценарии проходят, подумайте, может быть есть еще какие-то сценарии, которые вы не описали. Если так, то добавьте их.
 - Для аутентификации лучше всего использовать `Devise`, т.к. впоследствии он нам еще пригодится.

2021-03-03 11:28 UTC, vkurennov requested changes

2021-03-03 11:28 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      redirect_to question_path(@answer.question), alert: 'Your answer has not been created!'
тут нельзя делать редирект, т..к потеряется информация об ошибках валидации  и то, что ввел пользователь. сейчас ты через alert это решил, но это "костыль", т.к. валидаций может быть много и их надо брать из модели.
Решение: нужно рендерить страницу questions/show

2021-03-03 11:28 UTC, vkurennov commented on app/models/answer.rb
> +  belongs_to :user, optional: true
почему user optional? разве ответ без автора имеет смысл? это обязательный атрибут

2021-03-03 11:28 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +      .merge(user: current_user)
это лучше делать в экшене, потому что метод параметров задает только белый список допустимых параметров, но не должен из менять

2021-03-03 11:28 UTC, vkurennov commented on app/models/question.rb
> +  belongs_to :user, optional: true
тут это тоже обязательный атрибут

2021-03-03 11:28 UTC, vkurennov commented on config/routes.rb
>      resources :answers, shallow: true, except: :index
new и show кстати тоже не нужны, т.к. и форма и сами ответы на странице вопроса

2021-03-03 11:28 UTC, vkurennov commented on spec/features/answer/create_spec.rb
> +      expect(page).to have_content('Your answer has been successfully created!')
не нужно ставить скобки у методов вроде have_content, это DSL, у него не принято использовать скобки, там как раз цель в том, чтобы выражения были максимально похожи на естественный язык. А вот в своем коде как раз нужно ставить скобки у методов

2021-03-03 11:28 UTC, vkurennov commented on spec/helpers/application_helper_spec.rb
> +describe ApplicationHelper, type: :helper, aggregate_failures: true do
хелперы обычно не тестируют

2021-03-03 11:28 UTC, vkurennov commented on spec/models/user_spec.rb
> +describe User, type: :model do
нужны тесты на метод проверки автора, любой код, который ты пишешь в каком-либо классе должен иметь соответсвующие методы

2021-03-04 11:44 UTC, georgiybykov commented on app/models/answer.rb
> +  belongs_to :user, optional: true
Так это с какой стороны посмотреть. Если же вопросы и ответы могут читать другие люди (пользователи и гости), а первые из них далее оставлять ответы для вопроса удаленного пользователя с целью поделиться мнением/знанием с любым человеком, который будет читать, то имеет.

Ну это я к тому, как минимум, что не помню, что бы в задании где-то было условие на это.

Исправил на `touch: true` здесь и `dependent: :destroy` в модели юзера.

2021-03-04 12:09 UTC, georgiybykov commented on spec/models/user_spec.rb
> +describe User, type: :model do
Забыл, дописал

2021-03-04 12:19 UTC, georgiybykov commented on spec/helpers/application_helper_spec.rb
> +describe ApplicationHelper, type: :helper, aggregate_failures: true do
Не буду удалять, лишним не будет. Здесь я, на самом деле, просто пробовал делать экспектэйшн на разные виды ошибок и потом закоммитил файл.

> хелперы обычно не тестируют

Это бессмысленно или в чем причина?

2021-03-05 08:58 UTC, vkurennov commented on app/models/answer.rb
> +  belongs_to :user, optional: true
Ну да, тут дискуссионно и зависит от требований к системе - остаются ли ответы удаленного юезра? Но считаем, что у ответа обязательно должен быть автор в момент создания, а значит, ассоциация должна быть обязательной

2021-03-05 08:58 UTC, vkurennov commented on spec/helpers/application_helper_spec.rb
> +describe ApplicationHelper, type: :helper, aggregate_failures: true do
Скорее, это бессмысленно, это как приватные методы - некий внутренний вспомогательный код. Мы его работу тестируем опосредовнно, в данном случае, через фича-тесты

2021-03-05 08:59 UTC, vkurennov approved these changes

2021-03-05 22:25 UTC, georgiybykov commented on app/models/answer.rb
> +  belongs_to :user, optional: true
Вот и я об этом, что обсуждаемо или в ТЗ должно быть указано. Хорошо 👍

2021-03-05 22:27 UTC, georgiybykov commented on spec/helpers/application_helper_spec.rb
> +describe ApplicationHelper, type: :helper, aggregate_failures: true do
Да, тут, как частный случай, полностью согласен.
Но в хелперах порой бывает такой код, который безоговорочно требует тестирования.

2021-03-05 22:28 UTC, merged